services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  backend:
    build: ./Backend
    ports:
      - 8000:8000

  frontend:
    build: ./Frontend/isbit
    ports:
      - 3000:8080
    depends_on:
      - backend
