FROM python:3.12-slim

WORKDIR /backend

# Install build dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file
COPY ./requirements.txt /backend/requirements.txt

# Upgrade pip and install dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade -r /backend/requirements.txt --timeout=1000

# Copy the rest of the application code
COPY ./src /backend/src
COPY ./start.py /backend/start.py

# Expose the port the app will run on
EXPOSE 8000

# Define the command to run the application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
